### PR TITLE
Allow for passing until param.

### PR DESCRIPTION
**Pull request by dkinzer**
This commit allows the client to harvest a specific range not limited to
from until now.

Addendum:
* I noticed also that the from time and current until time seem to not include time granularity.  Maybe that should be corrected too?

### CODE REVIEW

**Comment by bibliotechy** [comment]
:+1: Looks like a pretty straightforward and useful addition.

**Comment by jrochkind** [comment]
I am now a committer/owner of this project. 

Happy to merge this if you are still interested -- but it probably needs a test?

**Comment by jrochkind** [comment]
One more try, I am a committer/owner, and could find some time to review/merge this is you are still interested, but I think it probably needs a test to be merged. If I don't hear, I may close this as outdated/abandoned, to clean things up. @dkinzer ?

**Comment by dkinzer** [comment]
@jrochkind I haven't been the official developer on the harvester for a while now; and the other developer started using python for this step.

However, I am back on that project now.  And I do believe this is still useful.  If I start using this gem I again, it would definitely come in handy.

Thanks @jrochkind!

**Comment by jrochkind** [comment]
In order to be merged, I think we need a test of some kind. Doesn't need to be perfect, but some kind of test that fails without this code there. Are you interested in adding a test, @dkinzer or @bibliotechy ?

I'm definitely in minimal caretaker mode, don't have time to do much code that isn't directly related to my needs, just trying to do a bit of cleanup while I'm stopping in.

**Comment by barmintor** [comment]
Ok, I've added a test rig for OAI::Harvester and a test case for this change. It was surprisingly involved, but I think this captures what @dkinzer was going for.

**Pull request merged**
