### PR TITLE
Remove explicit require for enumerator

### PR DESCRIPTION
**Pull request by mcritchlow**
should resolve: #84

### CODE REVIEW

**Review by orangewolf — APPROVED** [review]

**Comment by orangewolf** [comment]
also running in to this issue and would love to see it resolved

**Comment by jrochkind** [comment]
It looks like we basically don't have automated CI on this project anymore, because it's set up to run on travis, which doens't really support open source for free anymore. 

@mcritchlow @orangewolf if someone can confirm they have here that you have manually run tests on both ruby 2.6 and 2.7 and it passes, I’ll merge it for you.  And do a release? 

And… does someone else want to be added as a committer and gem releaser?  I am not really an active maintainer of this thing, but I do have commit and gem release privs on it, and came here after someone pinged me in Slack.

**Comment by orangewolf** [comment]
I can confirm that specs pass and code appears to work in both ruby 2.6 and 2.7

**Comment by jrochkind** [comment]
(Also how odd of ruby to break this on a 2.7 *patch* release, right?)

@mcritchlow would you like commit rights and gem release rights for this repo?

**Comment by jrochkind** [comment]
(Also... I'm somehow using ruby-oai in a project that uses ruby 3.0 without running into this problem, odd)

**Comment by mcritchlow** [comment]
> (Also how odd of ruby to break this on a 2.7 patch release, right?)

This was SO surprising to me too.

@jrochkind - thanks so much for the review. Yeah our Surfliner project (within the University of California system) has stood up an OAI-PMH app and will likely be engaged in this for a while. So I'd be happy to help out as needed here.

**Comment by jrochkind** [comment]
@mcritchlow and @orangewolf I have added you as committers. 

Please tell me your rubygems.org usernames, and I will add you as authorized gem releasers too. Then you can do a release if you like. 

I *do* still use ruby-oai in a project, but am not necessarily looking to invest much time in maintenance. But I may be the only person on the committer list who is still around at all, so I am adding you to to increase sustainability, decrease bus factor, and perhaps one or both of you are interested in doing some maintenance like getting CI working again or responding to other outstanding PRs.

**Pull request merged**
