### PR TITLE
Bump version to 1.2.0

### PR DESCRIPTION
**Pull request by mcritchlow**

### CODE REVIEW

**Comment by mcritchlow** [comment]
cc: @orangewolf

**Comment by barmintor** [comment]
Rebased against the RC tag to prep for release.

**Comment by mcritchlow** [comment]
@barmintor - I've done a review deployment of our application that uses this gem. test suite passes, and as far as I can tell so far everything looks good.

**Comment by barmintor** [comment]
Great to hear!

**Comment by orangewolf** [comment]
I tested this on a branch of Bulkrax - specs pass and I can still import OAI feeds. Looks good to me.

**Comment by barmintor** [comment]
Sounds good enough to cut the feature release!

**Pull request merged**
